# Generated by Django 5.0.7 on 2025-03-30 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_alter_loan_timestamp_alter_transactions_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='supports',
            name='support_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='supports',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 30, 6, 8, 41, 805555, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 30, 6, 8, 41, 805555, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 30, 6, 8, 41, 804554, tzinfo=datetime.timezone.utc)),
        ),
    ]
